---
deployment:
  tasks:
  - export DEPLOYPATH=/home3/roberwo4/public_html/
  - /bin/npm install
  - /bin/npm run build
  - /bin/rm -Rf $DEPLOYPATH
  - /bin/mkdir $DEPLOYPATH
  - /bin/cp -R build/ $DEPLOYPATH